### PR TITLE
Add simple NPM server

### PR DESCRIPTION
**Pull request by Taeir**
This allows for quick development by making use of the documentation pages.

### CODE REVIEW

**Comment by Taeir** [comment]
Hmm, looks like the idea was actually that eleventy would serve it (it seems upon further inspection), but there we no instructions or commands for that present in the package.json. I also can't get it to run correctly (it fails on what is in their own documentation like the first example).

**Comment by cellio** [comment]
> Hmm, looks like the idea was actually that eleventy would serve it (it seems upon further inspection), but there we no instructions or commands for that present in the package.json. I also can't get it to run correctly (it fails on what is in their own documentation like the first example).

Related? https://github.com/codidact/co-design/issues/86

**Comment by Taeir** [comment]
> Related?

Yes, that is the issue indeed... Should have looked a bit closer.

**Comment by Taeir** [comment]
Closing as I'm going to update eleventy instead.

**Pull request closed without merging**
