### PR TITLE
Theme

### PR DESCRIPTION
**Pull request by b-Istiak-s**
Resolves : https://github.com/codidact/co-design/issues/57 and, https://github.com/codidact/qpixel/issues/565

<details>
<summary>Dark theme</summary>

Screenshot 2021-08-17 at 21-32-58 Screenshot

</details>

Umm! [~~Code area (pre tag) and, user-card-meta's background is changed from cd.com/assets/stylesheets/application.scss That's why I didn't make changes to them in codidact.scss~~](https://github.com/codidact/qpixel/pull/634). ~~`button is-muted is-outlined is-active` (activity tab) is from codidact.scss. But, when I was copy-pasting those code I forgot to change their color and, background-color. I will change check it again.~~

Currently, I am using separated lines just to understand those code. In my last commit I will write them in a line (or, mix them).

<hr/>

Found a problem.... : ~~texts isn't white color in fields.. And, .notice .is-warning color is white.....~~ (Maybe, now I can say that no more work is needed in CoDesign) ~~(activity tab should be black (leaving it as it is for now))~~ (Check following picture and, comment if you see any problem)

<details>
<summary>New changes</summary>

Screenshot 2021-08-18 at 00-30-43 Screenshot

</details>

Note : Diff is showing that I made changes to light theme also. Usually, I make changes to light theme. It's all over dark theme.

To test (If you are using Linux) : If you are using Chrome/Chromium than, run that following way

```bash
google-chrome --force-dark-mode
chromium --force-dark-mode
```

You won't face problem for Firefox. I am not sure of Vilvera and, some others (Safari etc). Read [the thread](https://forum.manjaro.org/t/why-media-query-always-choosing-light-theme-css-html/77348/2?u=istiakshovon) to know why you are facing the problem.

Currently, most of worked are done. I guess, there's nothing "left". Usually, it is possible to change color for each category's header. I would request someone else to make changes for category's header (it's in line 17) (You can make PR in [the repo](https://github.com/Istiakshovon/co-design/tree/Theme) if you want). Current, category-header color isn't bad for dark theme either. But, new color for dark theme is very good. 

<hr/>

Ohh! Sorry I didn't know changing name of branch will delete PR

### CODE REVIEW

**Comment by luap42** [comment]
Um... where do you have the source files (/src) for these changes? If you don't include them, all modifications you made would be deleted at the next build.

**Comment by Istiakshovon** [comment]
Maybe, i didn’t understand you properly. Are you looking where I worked? https://github.com/Istiakshovon/co-design/tree/Theme the changes are available in that branch. I have those code in my system also

**Comment by ArtOfCode-** [comment]
@luap42 is right. You've changed the `dist/codidact.css` file with your changes, but nothing else. You need to make changes in the files under the `src/` directory, then run the build scripts to push them into `codidact.css` when that's done. Otherwise, next time we run a build all your changes will disappear.

**Review by ArtOfCode- — CHANGES_REQUESTED** [review]
.

**Comment by Istiakshovon** [comment]
@ArtOfCode- Where (Which line you changed) you requested to make changes? It's looking like you had made changes to Light Theme. When I was running your code I saw some weird text (Unicode) in post and lot of places. And, It wasn't available in dark theme.

Screenshot from 2021-08-18 16-05-45

**Comment by ArtOfCode-** [comment]
That's an encoding bug, don't know where from. There's no specific line you need to change - you need to move all your dark theme code into the appropriate files under src/ and then build the project to compile them into codidact.css.

**Comment by Istiakshovon** [comment]
@ArtOfCode- Please! Check that I am doing it correct or not.

**Comment by ArtOfCode-** [comment]
You've got the right files now, yep. Some tips:

 * Instead of hard-coding colour values, add them as variables as existing colors are.
 * Instead of wrapping all existing code in a light-mode media query and duplicating it in a dark mode query, you can *just* wrap lines that deal with colours in media queries.

**Comment by Istiakshovon** [comment]
Ohh! I forgot whenever I was running 

```bash
npm run build
```

I was getting some error.

<details>
<summary>error</summary>

Screenshot from 2021-08-18 20-56-48

</details>

`npm install` worked successfully. And, as far as I know my work is done.

**Review by ArtOfCode- — CHANGES_REQUESTED** [review]
You've still got hardcoded color values and entire blocks wrapped instead of single lines.

Use color variables instead: where light mode uses a color variable like `$bar-background-color`, go to `_variables.scss` and find that variable, and add another called something similar, like `$bar-dark-background-color`. Then instead of `#d0d0d0` in your code, you can use `$bar-dark-background-color`, and we only have to change it in one place.

As for wrapping things in media queries, if you've got this:

```scss
.thing {
  width: 100%;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  background: $thing-background-color;
  color: $thing-text-color;
}
```

Only the last two lines of that deal with colors, so instead of this:

```scss
/* avoid this way */
@media screen and (prefers-color-theme: light) {
  .thing {
    width: 100%;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    background: $thing-background-color;
    color: $thing-text-color;
  }
}
@media screen and (prefers-color-theme: dark) {
  .thing {
    width: 100%;
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    background: $thing-dark-background-color;
    color: $thing-dark-text-color;
  }
}
```

Just wrap the relevant lines in the media query:

```scss
.thing {
  width: 100%;
  display: flex;
  flex-direction: row;
  align-items: center;
  justify-content: center;
  background: $thing-background-color;
  color: $thing-text-color;

  @media screen and (prefers-color-scheme: dark) {
    background: $thing-dark-background-color;
    color: $thing-dark-text-color;
  }  
}
```

That way we default to light mode with overrides for dark mode. That both reduces code duplication and makes it more maintainable.

**Comment by Istiakshovon** [comment]
Oops! I forgot to made changes to codidact.scss. i will try to work on it again ASAP.

**Pull request closed without merging**
